language: php
php:
<<<<<<< HEAD
    - 7.1
    - 7.2
=======
    - 5.3.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm
>>>>>>> 252926673fbd6de211a39a1f51e16bcfeefff1e1

env:
    - PHP_BIN=php
    - PHP_BIN=php-cgi

<<<<<<< HEAD
before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - vendor/bin/tester -p $PHP_BIN tests -s
=======
matrix:
    allow_failures:
        - php: hhvm

    exclude:
        - php: hhvm
          env: PHP_BIN=php-cgi

script:
    - vendor/bin/tester -p $PHP_BIN tests -s
    - php code-checker/src/code-checker.php
>>>>>>> 252926673fbd6de211a39a1f51e16bcfeefff1e1

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

<<<<<<< HEAD
jobs:
    include:
        -   env: title="Lowest Dependencies" PHP_BIN=php
            install:
                - travis_retry composer update --no-progress --prefer-dist --prefer-lowest --prefer-stable


        -   stage: Code Standard Checker
            php: 7.1
            install:
                # Install Nette Code Checker
                - travis_retry composer create-project nette/code-checker temp/code-checker ~2 --no-progress
                # Install Nette Coding Standard
                - travis_retry composer create-project nette/coding-standard temp/coding-standard --no-progress

            script:
                - php temp/code-checker/src/code-checker.php --short-arrays --strict-types
                - php temp/coding-standard/ecs check src tests --config temp/coding-standard/coding-standard-php71.neon


        -   stage: Code Coverage
            php: 7.2
            script:
                - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
            after_script:
                - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
                - php coveralls.phar --verbose --config tests/.coveralls.yml


    allow_failures:
        -   stage: Code Coverage

=======
before_script:
    # Install Nette Tester & Code Checker
    - travis_retry composer install --no-interaction --prefer-dist
    - travis_retry composer create-project nette/code-checker code-checker ~2.5 --no-interaction
>>>>>>> 252926673fbd6de211a39a1f51e16bcfeefff1e1

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
<<<<<<< HEAD

notifications:
    email: false
=======
>>>>>>> 252926673fbd6de211a39a1f51e16bcfeefff1e1
